<?php

/**
 * @file
 * Contains participant_list.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\webform\WebformSubmissionInterface;

/**
 * Implements hook_help().
 */
function participant_list_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the participant_list module.
    case 'help.page.participant_list':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Visibilité de la liste des participants réservé aux organisateurs de la conférence.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function participant_list_theme() {
  return [
    'participant_list' => [
      'render element' => 'children',
    ],
  ];
}

// -- hook ajout et retrait des participant à un programme selon status adésion
function participant_list_webform_submission_update(WebformSubmissionInterface $entity) {
  // --
  $userId = $entity->getOwnerId();
  $members = $entity->getSourceEntity()->field_participants->getValue();
  
  //-- adhésion acceptée et utilisateur pas déja dans la liste
  if ($entity->getData()['adhesion_status'] == 'accepted' && !in_array(['target_id' => $userId], $members)) {
    $entity->getSourceEntity()->field_participants->setValue(array_merge($members, ['target_id' => $userId]));
    $entity->getSourceEntity()->save();
  }

  //-- adhésion refusée et utilisateur déja dans la liste
  if ($entity->getData()['adhesion_status'] != 'accepted' && in_array(['target_id' => $userId], $members)) {
    $key = array_search(['target_id' => $userId], $members);
    unset($members[$key]);

    $entity->getSourceEntity()->field_participants->setValue($members);
    $entity->getSourceEntity()->save();
  }
}